### ISSUE TITLE
Opdracht 1.2

### ISSUE THREAD

**Issue by pp-koch** [joanpadolina/browser-technologies-1920#1]
* een beschrijving van alle features die je hebt getest

	Erg goed.
	
* een beschrijving van de Devices en browsers waar je op hebt getest

	Goed.

* een beschrijving van de screenreader test

	Goed

* beschrijf hoe je de problemen hebt opgelost, of hoe je dit zou oplossen (met todo’s) als je genoeg tijd en budget zou hebben

	Problemen: goed. Alleen zie ik weinig oplossingen. 

	- Waarom werkt je site niet op de iPod? Deze ondersteunt wel degelijk JavaScript.
	- Wat ga je doen aan het tab-probleem dat je onder Mouse and Trackpad beschrijft?
	- Local storage: wat ga je doen als JavaScript wel aan staat, maar local storage uit?
	
	Als je deze drie dingen beschrijft, heb je de opdracht gehaald.

**Comment by joanpadolina** [comment]
bij elk probleem in de feedback heb ik een "possible solution" of "tips and tricks" beschreven. 
[Bij het ipod probleem](https://github.com/joanpadolina/browser-technologies-1920/wiki/Three-devices)
[tab in firefox & localstorage](https://github.com/joanpadolina/browser-technologies-1920/wiki/Different-Browser)

**Comment by pp-koch** [comment]
Prima, dank je. Je hebt 'm gehaald,
