### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by chelseadoeleman** [joanpadolina/browser-technologies-1920#2]
Hi Joan! 

**What are the most important things to include in the readme?**
Voornamelijk je onderzoek naar verschillende features en hoe het wordt ondersteund, verwijs naar hierbij naar bronnen. Documenteer ook eventuele tests in verschillende browsers en op devices, wat zie je? Afbeeldingen zijn hier heel nice bij! 😊 En natuurlijk de beschrijving van de lagen, maar zo te zien staat dit al in je wiki, link hier vooral naar vanuit je Repo! 

Hoe heb jij op verschillende features getest en wat waren de uitkomsten hiervan, van jouw applicatie. Hoe heb je feature detection en @supports gebruikt, hier kun je (code)voorbeelden van laten zien. Hoop dat dit wat meer duidelijkheid geeft en anders kun je kijken in de [rubric](https://docs.google.com/spreadsheets/d/1MV3BWwwg_Zz1n-S_qOM4iSm4gA4M6g0xAxGacyaPuac/edit#gid=0), door te kijken of je deze onderdelen uitlegt in je readme.

**How do you begin with researching your feature**
Je zou kunnen beginnen met het uitzoeken van de onderdelen, die je in jouw applicatie nodig hebt. Vervolgens te onderzoeken hoe deze onderdelen worden ondersteund met bijv [caniuse](https://caniuse.com/) of [quirksmode](https://quirksmode.org/) of andere sources. Daarna natuurlijk testen, om te kijken of het daadwerkelijk ook werkt :), vooral in oudere browsers is niets wat het lijkt. Vraag vooral aan anderen hoe zij dit aanpakken! Het testen van andere features heb je waarschijnlijk al uitgezocht in opdracht 1.2. Ik hoop dat je hier iets aan hebt en anders laat je het maar weten! 

**Wiki**
Ik zal dit even navragen, want ik zie hier niks over staan in de rubric. Anderen splitten het op in onderzoek in de wiki en de hoofdonderwerpen in je Readme, maar lang niet iedereen doet dit. Vergeet dan niet vanuit je Readme te linken naar je Wiki evt. 

**Algemeen**
```js
<fieldset>
        <input type="button" value="save">
        <input type="submit" value="print">
    </fieldset>
```
In je code zag ik dit stukje voorbij komen. Gebruik je input met een bepaalde reden als submit, want volgens mij kun je hier ook een button voor gebruiken! Buttons kunnen ook een value hebben 😊. Verder lekker bezig, ga zo door!

**Comment by joanpadolina** [comment]
I hope I've added enough thank you
